services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api
    container_name: comfort-frontend
    restart: unless-stopped
    ports:
      - '5173:80'
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
